FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json yarn.lock turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN yarn install
# Can you add a script to the global package.json that does this?
RUN yarn run db:generate

# Can you filter the build down to just one app?
RUN yarn run build

CMD ["yarn", "run", "start-user-app"]